#pragma once

#include "open62541pp/open62541.h"

#include <inttypes.h>

/**
 * @brief The attribute IDs. For more information, see common.h.
 */
enum class AttributeId : uint32_t {
    NODE_ID = UA_ATTRIBUTEID_NODEID,
    NODE_CLASS = UA_ATTRIBUTEID_NODECLASS,
    BROWSE_NAME = UA_ATTRIBUTEID_BROWSENAME,
    DISPLAY_NAME = UA_ATTRIBUTEID_DISPLAYNAME,
    DESCRIPTION = UA_ATTRIBUTEID_DESCRIPTION,
    WRITEMASK = UA_ATTRIBUTEID_WRITEMASK,
    USER_WRITE_MASK = UA_ATTRIBUTEID_USERWRITEMASK,
    IS_ABSTRACT = UA_ATTRIBUTEID_ISABSTRACT,
    SYMMETRIC = UA_ATTRIBUTEID_SYMMETRIC,
    INVERSE_NAME = UA_ATTRIBUTEID_INVERSENAME,
    CONTAINS_NO_LOOPS = UA_ATTRIBUTEID_CONTAINSNOLOOPS,
    EVENT_NOTIFIER = UA_ATTRIBUTEID_EVENTNOTIFIER,
    VALUE = UA_ATTRIBUTEID_VALUE,
    DATATYPE = UA_ATTRIBUTEID_DATATYPE,
    VALUE_RANK = UA_ATTRIBUTEID_VALUERANK,
    ARRAY_DIMENSIONS = UA_ATTRIBUTEID_ARRAYDIMENSIONS,
    ACCESS_LEVEL = UA_ATTRIBUTEID_ACCESSLEVEL,
    USER_ACCESS_LEVEL = UA_ATTRIBUTEID_USERACCESSLEVEL,
    MINIMUM_SAMPLING_INTERVAL = UA_ATTRIBUTEID_MINIMUMSAMPLINGINTERVAL,
    HISTORIZING = UA_ATTRIBUTEID_HISTORIZING,
    EXECUTABLE = UA_ATTRIBUTEID_EXECUTABLE,
    USER_EXECUTABLE = UA_ATTRIBUTEID_USEREXECUTABLE,
    DATA_TYPE_DEFINITION = UA_ATTRIBUTEID_DATATYPEDEFINITION,
    ROLE_PERMISSIONS = UA_ATTRIBUTEID_ROLEPERMISSIONS,
    USER_ROLE_PERMISSIONS = UA_ATTRIBUTEID_USERROLEPERMISSIONS,
    ACCESS_RESTRICTIONS = UA_ATTRIBUTEID_ACCESSRESTRICTIONS,
    ACCESS_LEVEL_EX = UA_ATTRIBUTEID_ACCESSLEVELEX
};

/**
 * @brief The UA_NodeAttributesMask type. Check types_generated.h for more information.
 */
enum class NodeAttributeMask : uint32_t {
    NONE = UA_NODEATTRIBUTESMASK_NONE,
    ACCESS_LEVEL = UA_NODEATTRIBUTESMASK_ACCESSLEVEL,
    ARRAY_DIMENSIONS = UA_NODEATTRIBUTESMASK_ARRAYDIMENSIONS,
    BROWSE_NAME = UA_NODEATTRIBUTESMASK_BROWSENAME,
    CONTAINS_NO_LOOPS = UA_NODEATTRIBUTESMASK_CONTAINSNOLOOPS,
    DATA_TYPE = UA_NODEATTRIBUTESMASK_DATATYPE,
    DESCRIPTION = UA_NODEATTRIBUTESMASK_DESCRIPTION,
    DISPLAY_NAME = UA_NODEATTRIBUTESMASK_DISPLAYNAME,
    EVENT_NOTIFIER = UA_NODEATTRIBUTESMASK_EVENTNOTIFIER,
    EXECUTABLE = UA_NODEATTRIBUTESMASK_EXECUTABLE,
    HISTORIZING = UA_NODEATTRIBUTESMASK_HISTORIZING,
    INVERSE_NAME = UA_NODEATTRIBUTESMASK_INVERSENAME,
    ISABSTRACT = UA_NODEATTRIBUTESMASK_ISABSTRACT,
    MINIMUM_SAMPLING_INTERVAL = UA_NODEATTRIBUTESMASK_MINIMUMSAMPLINGINTERVAL,
    NODE_CLASS = UA_NODEATTRIBUTESMASK_NODECLASS,
    NODE_ID = UA_NODEATTRIBUTESMASK_NODEID,
    SYMMETRIC = UA_NODEATTRIBUTESMASK_SYMMETRIC,
    USER_ACCESS_LEVEL = UA_NODEATTRIBUTESMASK_USERACCESSLEVEL,
    USER_EXECUTABLE = UA_NODEATTRIBUTESMASK_USEREXECUTABLE,
    USER_WRITE_MASK = UA_NODEATTRIBUTESMASK_USERWRITEMASK,
    VALUE_RANK = UA_NODEATTRIBUTESMASK_VALUERANK,
    WRITEMASK = UA_NODEATTRIBUTESMASK_WRITEMASK,
    VALUE = UA_NODEATTRIBUTESMASK_VALUE,
    DATA_TYPE_DEFINITION = UA_NODEATTRIBUTESMASK_DATATYPEDEFINITION,
    ROLE_PERMISSIONS = UA_NODEATTRIBUTESMASK_ROLEPERMISSIONS,
    ACCESS_RESTRICTIONS = UA_NODEATTRIBUTESMASK_ACCESSRESTRICTIONS,
    ALL = UA_NODEATTRIBUTESMASK_ALL,
    BASE_NODE = UA_NODEATTRIBUTESMASK_BASENODE,
    OBJECT = UA_NODEATTRIBUTESMASK_OBJECT,
    OBJECT_TYPE = UA_NODEATTRIBUTESMASK_OBJECTTYPE,
    VARIABLE = UA_NODEATTRIBUTESMASK_VARIABLE,
    VARIABLE_TYPE = UA_NODEATTRIBUTESMASK_VARIABLETYPE,
    METHOD = UA_NODEATTRIBUTESMASK_METHOD,
    REFERENCE_TYPE = UA_NODEATTRIBUTESMASK_REFERENCETYPE,
    VIEW = UA_NODEATTRIBUTESMASK_VIEW,
    FORCE32BIT = __UA_NODEATTRIBUTESMASK_FORCE32BIT,
};