#pragma once

#include "open62541pp/open62541.h"

enum class MonitoringMode : UA_Int32 {
    DISABLED = UA_MONITORINGMODE_DISABLED,
    SAMPLING = UA_MONITORINGMODE_SAMPLING,
    REPORTING = UA_MONITORINGMODE_REPORTING,
    FORCE32BIT = __UA_MONITORINGMODE_FORCE32BIT
} ;